# Autogenerated by fastlane
#
# Ensure this file is checked in to source control!
#ruby-gemset=streem
#ruby=2.4.4
ruby "2.4.4"

source "https://rubygems.org"

gem 'cocoapods', '~>1.8.0'
gem 'psych', '~>2.2.2'
gem "fastlane", "~> 2.132"

plugins_path = File.join(File.dirname(__FILE__), 'fastlane', 'Pluginfile')
eval_gemfile(plugins_path) if File.exist?(plugins_path)

gem "cocoapods-check", "~> 1.0"
