source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/twilio/cocoapod-specs.git'

use_frameworks!

platform :ios, '11.3'

target 'StreemNow' do
	pod 'StreemKit', :path => '../'
end

target 'StreemNow_Tests' do
	inherit! :search_paths

	pod 'Quick', '~> 1.3.2'
	pod 'Nimble', '~> 8'
	pod 'FBSnapshotTestCase' , '~> 2.1.4'
	pod 'Nimble-Snapshots' , '~> 7'
	pod 'StreemKit', :path => '../'
end

post_install do |installer|
	installer.pods_project.targets.each do |target|
		target.build_configurations.each do |config|
			# For now, no optimization.
			# This prevents inlining into the Streem framework of
			# allocations of RxSwift objects. Such inlined allocations
			# lead to crashes due to differences in the size of
			# those objects for Debug vs. Release builds of RxSwift.
			config.build_settings['SWIFT_OPTIMIZATION_LEVEL'] = '-Onone'
			#
			# For now, always build as Swift 4.2.
			config.build_settings['SWIFT_VERSION'] = '4.2'
			#
			# This allows us to build for use in Swift 5.1.2
			config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
		end
	end
end
