source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/streem/cocoapods.git'

use_frameworks!

platform :ios, '14.0'

target 'GuidedScanNow' do
	pod 'StreemGuidedScanKit', '0.8.0-swift55'
	pod 'AppAuth', '~> 1.4'
end

post_install do |installer|
	load './Pods/StreemGuidedScanKit/configure_guidedscankit.rb'
	configure_guidedscankit(installer)
end
